### ISSUE TITLE
Fatal error after module installation

### ISSUE THREAD

**Issue by sebastien-cas** [alma/alma-installments-magento1#7]
Hello,
After copied modules files, clear cache and gone to the configuration panel, I obtain this fatal error:
`Fatal error: Uncaught Error: Call to a member function feePlans() on null in /var/www/openmage/src/app/code/community/Alma/Installments/Helper/FeePlansHelper.php:71`

It's logic because in file FeePlansHelper.php you try to execut feePlans method on null.
`$almaFeePlans = $this->almaClient->merchants->feePlans();`
Logic because you try to get default client and execute this code:
`$this->alma = $this->createInstance($this->config->getActiveAPIKey(), $this->config->getActiveMode());`

But ApiKey is not set yet! I need that module works fine to set ApiKey.
So client is not defined and fatal error appears.

**Comment by Francois-Gomis** [comment]
Hi,
thank you for your comment, i check this issue quickly.

**Comment by Francois-Gomis** [comment]
Hi,
it's solved in new version 2.1.1.
Thanks.
